[package]
name = "clock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
chrono = "0.4.22"
clap = "2"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.137"